import os

GOOGLE_CLOUD_API_KEY_PATH = os.environ.get('GOOGLE_CLOUD_API_KEY_PATH')
MONGODB_CONNECTION_STRING = os.environ.get('MONGODB_CONNECTION_STRING')
MONGODB_DATABASE_NAME = os.environ.get('MONGODB_DATABASE_NAME')